name: Main CI-pipeline

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Checkstyle
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test with coverage
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutput=coverage.cobertura.xml /p:CoverletOutputFormat=cobertura /p:Threshold=90 /p:ThresholdType=line /p:ThresholdStat=total

      - name: Coverage comment
        uses: bibipkins/dotnet-test-reporter@v1.6.1
        if: hashFiles('./TestResults/*.trx') != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Unit Test Results'
          results-path: ./TestResults/*.trx
          coverage-path: ./TestResults/coverage.xml
          coverage-threshold: 90